--[[
Same-platform and profiled onedir bundler for luainstaller.

Author:
    WaterRun
File:
    bundler.lua
Date:
    2026-06-21
Updated:
    2026-06-21
]]

local launcher = require("luainstaller.launcher")
local platform = require("luainstaller.platform")

local M = {}

local PATH_SEP = package.config:sub(1, 1)
local IS_WINDOWS = PATH_SEP == "\\"

local function makeError(err_type, message, details)
    local err = {
        type = err_type,
        message = message,
    }
    if details then
        for k, v in pairs(details) do
            err[k] = v
        end
    end
    return {
        ok = false,
        error = err,
    }
end

local function normalizePath(path)
    path = tostring(path or ""):gsub("\\", "/")
    local prefix = ""
    if path:match("^//") then
        prefix = "//"
        path = path:sub(3)
    elseif path:match("^%a:/") then
        prefix = path:sub(1, 3)
        path = path:sub(4)
    elseif path:sub(1, 1) == "/" then
        prefix = "/"
        path = path:sub(2)
    end

    local parts = {}
    for segment in path:gmatch("[^/]+") do
        if segment == ".." then
            if #parts > 0 and parts[#parts] ~= ".." then
                parts[#parts] = nil
            elseif prefix == "" then
                parts[#parts + 1] = ".."
            end
        elseif segment ~= "." and segment ~= "" then
            parts[#parts + 1] = segment
        end
    end

    local result = prefix .. table.concat(parts, "/")
    if result == "" then
        return "."
    end
    return result
end

local function isAbsolutePath(path)
    return path:sub(1, 1) == "/" or path:match("^%a:/") ~= nil
end

local function commandOutput(command)
    if type(io.popen) ~= "function" then
        return false, "io.popen is not available in this Lua runtime"
    end
    local popen_ok, pipe = pcall(io.popen, command .. " 2>&1", "r")
    if not popen_ok or not pipe then
        return false, tostring(pipe)
    end
    local output = pipe:read("*a") or ""
    local ok = pipe:close()
    if ok == true or ok == 0 then
        return true, output
    end
    return false, output
end

local function currentDirectory()
    local ok, dir = commandOutput(IS_WINDOWS and "cd" or "pwd")
    if ok then
        local first_line = dir:match("^[^\r\n]+")
        if first_line and first_line ~= "" then
            return normalizePath(first_line)
        end
    end
    return "."
end

local function absolutePath(path)
    path = normalizePath(path)
    if isAbsolutePath(path) then
        return path
    end
    return normalizePath(currentDirectory() .. "/" .. path)
end

local function dirname(path)
    path = normalizePath(path)
    return path:match("^(.+)/[^/]+$") or "."
end

local function basename(path)
    path = normalizePath(path)
    return path:match("[^/]+$") or path
end

local function stem(path)
    local name = basename(path)
    return name:match("^(.+)%.[^%.]+$") or name
end

local function shellQuote(value)
    value = tostring(value or "")
    return "'" .. value:gsub("'", "'\\''") .. "'"
end

local function ensureDirectory(path)
    local ok, output = commandOutput("mkdir -p " .. shellQuote(path))
    if not ok then
        return makeError("FilesystemError", "Cannot create directory: " .. tostring(path), {
            output = output,
            path = path,
        })
    end
    return nil
end

local function removeTree(path)
    local ok, output = commandOutput("rm -rf " .. shellQuote(path))
    if not ok then
        return makeError("FilesystemError", "Cannot remove directory: " .. tostring(path), {
            output = output,
            path = path,
        })
    end
    return nil
end

local function fileExists(path)
    local file = io.open(path, "rb")
    if not file then
        return false
    end
    file:close()
    return true
end

local function pathExists(path)
    local ok = commandOutput("test -e " .. shellQuote(path))
    return ok == true
end

local function directoryExists(path)
    local ok = commandOutput("test -d " .. shellQuote(path))
    return ok == true
end

local function isSymlink(path)
    local ok = commandOutput("test -L " .. shellQuote(path))
    return ok == true
end

local function directoryIsEmpty(path)
    local ok, output = commandOutput("find " .. shellQuote(path) .. " -mindepth 1 -maxdepth 1 | head -n 1")
    return ok and output == ""
end

local function hasGeneratedManifest(path)
    local manifest_path = normalizePath(path .. "/.luai/manifest.lua")
    local file = io.open(manifest_path, "rb")
    if not file then
        return false
    end
    local prefix = file:read(#"-- generated by luainstaller") or ""
    file:close()
    return prefix == "-- generated by luainstaller"
end

local function generatedDirectoryHasOnlyAllowedEntries(path, allowed)
    local ok, output = commandOutput("find " .. shellQuote(path) .. " -mindepth 1 -maxdepth 1")
    if not ok then
        return false, output
    end
    for line in output:gmatch("[^\n]+") do
        local name = basename(line)
        if not allowed[name] then
            return false, line
        end
    end
    return true
end

local function validateLuaPrefix(prefix)
    if type(prefix) ~= "string" or prefix == "" then
        return makeError("ToolchainError", "Lua prefix is required for this onedir target")
    end
    local include = normalizePath(prefix .. "/include/lua.h")
    local liblua = normalizePath(prefix .. "/lib/liblua.a")
    if not fileExists(include) or not fileExists(liblua) then
        return makeError("ToolchainError", "Lua prefix must contain include/lua.h and lib/liblua.a", {
            lua_prefix = prefix,
        })
    end
    return nil
end

local function validateWindowsLuaPrefix(prefix)
    if type(prefix) ~= "string" or prefix == "" then
        return makeError("ToolchainError", "Lua prefix is required for windows onedir target")
    end
    local include = normalizePath(prefix .. "/include/lua.h")
    if not fileExists(include) then
        return makeError("ToolchainError", "Windows Lua prefix must contain include/lua.h", {
            lua_prefix = prefix,
        })
    end
    local candidates = {
        normalizePath(prefix .. "/bin/lua54.dll"),
        normalizePath(prefix .. "/lua54.dll"),
        normalizePath(prefix .. "/bin/lua.dll"),
        normalizePath(prefix .. "/lua.dll"),
    }
    for _, candidate in ipairs(candidates) do
        if fileExists(candidate) then
            return nil, {
                include_dir = normalizePath(prefix .. "/include"),
                dll_path = candidate,
                dll_dir = dirname(candidate),
                dll_name = basename(candidate),
                library_name = (basename(candidate):gsub("%.dll$", "")),
            }
        end
    end
    return makeError("ToolchainError", "Windows Lua prefix must contain bin/lua54.dll or lua54.dll", {
        lua_prefix = prefix,
    })
end

local function writeFile(path, content)
    local file = io.open(path, "wb")
    if not file then
        return makeError("FilesystemError", "Cannot write file: " .. tostring(path), {
            path = path,
        })
    end
    file:write(content or "")
    file:close()
    return nil
end

local function copyFile(source, destination)
    local dir_err = ensureDirectory(dirname(destination))
    if dir_err then
        return dir_err
    end
    local ok, output = commandOutput("cp " .. shellQuote(source) .. " " .. shellQuote(destination))
    if not ok then
        return makeError("FilesystemError", "Cannot copy file: " .. tostring(source), {
            source = source,
            destination = destination,
            output = output,
        })
    end
    return nil
end

local function findLinkedLuaRuntime(exe_path)
    local ok, output = commandOutput("ldd " .. shellQuote(exe_path))
    if not ok then
        return nil, output
    end
    for line in output:gmatch("[^\n]+") do
        local name, path = line:match("^%s*(liblua[^%s]*)%s+=>%s+([^%s]+)")
        if name and path and path ~= "not" then
            return path, name
        end
        path = line:match("^%s*(/[^%s]*liblua[^%s]*)")
        if path then
            return path, basename(path)
        end
    end
    return nil, output
end

local function copyLuaRuntime(exe_path, native_dir)
    local lua_path, lua_name = findLinkedLuaRuntime(exe_path)
    if not lua_path then
        return makeError("LuaRuntimeNotFoundError", "Cannot locate linked Lua shared library", {
            executable = exe_path,
            output = lua_name,
        })
    end
    local destination = normalizePath(native_dir .. "/" .. lua_name)
    local err = copyFile(lua_path, destination)
    if err then
        return err
    end
    return nil, {
        source_path = normalizePath(lua_path),
        destination_path = normalizePath(".luai/native/" .. lua_name),
    }
end

local function sortedKeys(tbl)
    local keys = {}
    for key in pairs(tbl) do
        keys[#keys + 1] = key
    end
    table.sort(keys, function(left, right)
        if type(left) == type(right) then
            return left < right
        end
        return tostring(left) < tostring(right)
    end)
    return keys
end

local function isArray(tbl)
    local count = 0
    local max_index = 0
    for key in pairs(tbl) do
        if type(key) ~= "number" or key < 1 or key ~= math.floor(key) then
            return false
        end
        count = count + 1
        if key > max_index then
            max_index = key
        end
    end
    return max_index == count
end

local function serializeValue(value, indent)
    indent = indent or ""
    local value_type = type(value)
    if value_type == "string" then
        return string.format("%q", value)
    end
    if value_type == "number" or value_type == "boolean" then
        return tostring(value)
    end
    if value_type == "nil" then
        return "nil"
    end
    if value_type ~= "table" then
        return string.format("%q", tostring(value))
    end

    local child_indent = indent .. "    "
    local lines = { "{" }
    if isArray(value) then
        for i = 1, #value do
            lines[#lines + 1] = child_indent .. serializeValue(value[i], child_indent) .. ","
        end
    else
        for _, key in ipairs(sortedKeys(value)) do
            local key_text
            if type(key) == "string" and key:match("^[%a_][%w_]*$") then
                key_text = key
            else
                key_text = "[" .. serializeValue(key, child_indent) .. "]"
            end
            lines[#lines + 1] = child_indent .. key_text .. " = " .. serializeValue(value[key], child_indent) .. ","
        end
    end
    lines[#lines + 1] = indent .. "}"
    return table.concat(lines, "\n")
end

local function serializeManifest(manifest)
    return "-- generated by luainstaller\nreturn " .. serializeValue(manifest, "")
end

local function executableName(out_path, entry, profile)
    local name = basename(out_path or "")
    if name == "" or name == "." then
        name = stem(entry)
    end
    local suffix = profile and profile.executable_suffix or ""
    if suffix ~= "" and not name:lower():match(suffix:gsub("%.", "%%.") .. "$") then
        name = name .. suffix
    elseif IS_WINDOWS and suffix == "" and not name:lower():match("%.exe$") then
        name = name .. ".exe"
    end
    return name
end

local function windowsCompiler()
    return os.getenv("LUAI_WINDOWS_CC") or "x86_64-w64-mingw32-gcc"
end

local function defaultOut(entry)
    return normalizePath("build/" .. stem(entry))
end

local function linuxHost()
    local ok, output = commandOutput("uname -s")
    return ok and output:match("^Linux") ~= nil
end

local function unsafeOutputError(path)
    return makeError("InvalidOutputError", "Refusing to overwrite unsafe output directory: " .. tostring(path), {
        path = path,
    })
end

local function validateOutputDirectory(path, allowed_generated_entries)
    local normalized = normalizePath(path)
    if normalized == "/" or normalized == "." or normalized == "" then
        return unsafeOutputError(path)
    end
    if normalized == currentDirectory() then
        return unsafeOutputError(path)
    end
    if isSymlink(normalized) then
        return unsafeOutputError(path)
    end
    if pathExists(normalized) then
        if not directoryExists(normalized) then
            return makeError("InvalidOutputError", "Output path exists and is not a directory: " .. tostring(path), {
                path = path,
            })
        end
        local empty = directoryIsEmpty(normalized)
        local generated = not empty and hasGeneratedManifest(normalized)
        if not empty and not generated then
            return makeError("InvalidOutputError", "Refusing to overwrite non-luainstaller output directory: " .. tostring(path), {
                path = path,
            })
        end
        if generated then
            local generated_only, unexpected = generatedDirectoryHasOnlyAllowedEntries(normalized, allowed_generated_entries or {})
            if not generated_only then
                return makeError("InvalidOutputError", "Refusing to overwrite luainstaller output directory with unexpected files: " .. tostring(path), {
                    path = path,
                    unexpected_path = unexpected,
                })
            end
        end
    end
    return nil
end

local function traceModuleMaps(trace)
    local lua_names = {}
    local native_names = {}
    for _, item in ipairs(trace or {}) do
        if item.selected_path and item.requested then
            if item.classification == "lua" or item.selected_type == "lua" then
                lua_names[normalizePath(item.selected_path)] = item.requested
            elseif item.classification == "native" or item.selected_type == "native" then
                native_names[normalizePath(item.selected_path)] = item.requested
            end
        end
    end
    return lua_names, native_names
end

local function nativeDestinations(native_path, module_name, native_dir)
    local destinations = {}
    local seen = {}
    local function add(path)
        path = normalizePath(path)
        if not seen[path] then
            seen[path] = true
            destinations[#destinations + 1] = path
        end
    end

    add(native_dir .. "/" .. basename(native_path))
    if module_name and module_name ~= "" then
        local ext = basename(native_path):match("(%.[^%.]+)$") or ".so"
        add(native_dir .. "/" .. module_name:gsub("%.", "/") .. ext)
    end
    return destinations
end

function M.bundleOnedir(opts)
    opts = opts or {}
    if type(io.popen) ~= "function" then
        return makeError("ToolchainError", "io.popen is required to build onedir bundles")
    end

    local profile = platform.profile({
        target_os = opts.target_os,
        lua_prefix = opts.lua_prefix,
    })
    local windows_lua
    if profile.target_os == "windows" then
        if not linuxHost() then
            return makeError("UnsupportedPlatformError", "windows onedir bundling requires a Linux host with MinGW")
        end
        local prefix_err
        prefix_err, windows_lua = validateWindowsLuaPrefix(profile.lua_prefix)
        if prefix_err then
            return prefix_err
        end
        local cc_ok, cc_output = commandOutput(windowsCompiler() .. " --version")
        if not cc_ok then
            return makeError("ToolchainError", "Windows onedir bundling requires x86_64-w64-mingw32-gcc", {
                output = cc_output,
            })
        end
    elseif profile.target_os == "macos" then
        local prefix_err = validateLuaPrefix(profile.lua_prefix)
        if prefix_err then
            return prefix_err
        end
    elseif profile.target_os == "linux" then
        if not linuxHost() then
            return makeError("UnsupportedPlatformError", "linux onedir bundling requires a Linux host")
        end
    else
        return makeError("UnsupportedPlatformError", "unsupported onedir target: " .. tostring(profile.target_os))
    end

    local manifest = opts.manifest
    local dependencies = opts.dependencies or { scripts = {}, libraries = {} }
    local entry = opts.entry
    if type(manifest) ~= "table" then
        return makeError("InvalidOptionsError", "manifest is required")
    end
    if type(entry) ~= "string" or entry == "" then
        return makeError("InvalidOptionsError", "entry is required")
    end

    local out_dir = absolutePath(opts.out or defaultOut(entry))
    local exe_name = executableName(out_dir, entry, profile)
    local allowed_generated_entries = {
        [".luai"] = true,
        [exe_name] = true,
    }
    if windows_lua then
        allowed_generated_entries[windows_lua.dll_name] = true
    end
    local output_err = validateOutputDirectory(out_dir, allowed_generated_entries)
    if output_err then
        return output_err
    end

    local exe_path = normalizePath(out_dir .. "/" .. exe_name)
    local luai_dir = normalizePath(out_dir .. "/.luai")
    local native_dir = normalizePath(luai_dir .. "/native")
    local build_dir = normalizePath(luai_dir .. "/build")
    local c_path = normalizePath(build_dir .. "/launcher.c")

    local err = removeTree(out_dir) or ensureDirectory(native_dir) or ensureDirectory(build_dir)
    if err then
        return err
    end

    local lua_names, native_names = traceModuleMaps(opts.trace or manifest.trace or {})
    local c_source
    local ok_generate, generated = pcall(launcher.generateSource, {
        entry = entry,
        dependencies = dependencies,
        module_names = lua_names,
        native_dir = ".luai/native",
    })
    if not ok_generate then
        return makeError("LauncherGenerationError", tostring(generated))
    end
    c_source = generated

    err = writeFile(c_path, c_source)
    if err then
        return err
    end

    for _, path in ipairs(dependencies.libraries or {}) do
        local normalized = normalizePath(path)
        for _, destination in ipairs(nativeDestinations(normalized, native_names[normalized], native_dir)) do
            err = copyFile(normalized, destination)
            if err then
                return err
            end
        end
    end

    local compile_cmd
    if profile.target_os == "windows" then
        compile_cmd = table.concat({
            shellQuote(windowsCompiler()),
            shellQuote(c_path),
            "-I" .. shellQuote(windows_lua.include_dir),
            "-L" .. shellQuote(windows_lua.dll_dir),
            "-o",
            shellQuote(exe_path),
            "-static-libgcc",
            "-l" .. windows_lua.library_name,
        }, " ")
    elseif profile.target_os == "macos" then
        compile_cmd = table.concat({
            "cc",
            shellQuote(c_path),
            "-I" .. shellQuote(profile.lua_prefix .. "/include"),
            "-o",
            shellQuote(exe_path),
            "-Wl,-rpath," .. shellQuote(profile.loader_rpath),
            shellQuote(profile.lua_prefix .. "/lib/liblua.a"),
            "-lm",
        }, " ")
    else
        local pkg_ok, pkg_flags = commandOutput("pkg-config --cflags --libs lua")
        if not pkg_ok then
            return makeError("ToolchainError", "pkg-config cannot find lua", {
                output = pkg_flags,
            })
        end

        local cleaned_pkg_flags = (pkg_flags:gsub("%s+$", ""))
        compile_cmd = table.concat({
            "cc",
            shellQuote(c_path),
            "-o",
            shellQuote(exe_path),
            "-Wl,-rpath," .. shellQuote(profile.loader_rpath),
            cleaned_pkg_flags,
        }, " ")
    end
    local compile_ok, compile_output = commandOutput(compile_cmd)
    if not compile_ok then
        return makeError("CompilationFailedError", "C launcher compilation failed", {
            command = compile_cmd,
            output = compile_output,
        })
    end

    if profile.target_os ~= "windows" then
        commandOutput("chmod +x " .. shellQuote(exe_path))
    end

    if profile.target_os == "windows" then
        local exe_dll = normalizePath(out_dir .. "/" .. windows_lua.dll_name)
        err = copyFile(windows_lua.dll_path, exe_dll)
        if err then
            return err
        end
        local native_dll = normalizePath(native_dir .. "/" .. windows_lua.dll_name)
        err = copyFile(windows_lua.dll_path, native_dll)
        if err then
            return err
        end
        manifest.launcher.lua_runtime = {
            source_path = normalizePath(windows_lua.dll_path),
            destination_path = windows_lua.dll_name,
            native_destination_path = normalizePath(".luai/native/" .. windows_lua.dll_name),
            link_mode = "shared-dll",
        }
    elseif profile.target_os == "macos" then
        manifest.launcher.lua_runtime = {
            source_path = normalizePath(profile.lua_prefix .. "/lib/liblua.a"),
            destination_path = nil,
            link_mode = "static",
        }
    else
        local runtime_record
        err, runtime_record = copyLuaRuntime(exe_path, native_dir)
        if err then
            return err
        end
        manifest.launcher.lua_runtime = runtime_record
    end

    err = writeFile(normalizePath(luai_dir .. "/manifest.lua"), serializeManifest(manifest))
    if err then
        return err
    end

    return {
        ok = true,
        action = "bundle",
        mode = "onedir",
        entry = entry,
        out = out_dir,
        executable = exe_path,
        manifest = manifest,
    }
end

return M
