--[[
Shared-Lua C launcher source generation for luainstaller.

Author:
    WaterRun
File:
    launcher.lua
Date:
    2026-06-16
Updated:
    2026-06-16
]]

local cgen = require("luainstaller.cgen")

local M = {}

local DEFAULT_TEMPLATE_PATH = "src/launcher/luai_launcher.c"

local function readFile(path)
    local handle = io.open(path, "rb")
    if not handle then
        error({
            type = "LauncherTemplateNotFoundError",
            message = "Cannot read launcher template: " .. tostring(path),
            path = path,
        })
    end
    local content = handle:read("*a")
    handle:close()
    return content or ""
end

function M.bytesFromString(source)
    source = tostring(source or "")
    local bytes = {}
    for i = 1, #source do
        bytes[#bytes + 1] = string.format("0x%02X", source:byte(i))
    end
    return bytes
end

local function emitBytes(name, source)
    local bytes = M.bytesFromString(source)
    local lines = {}
    lines[#lines + 1] = "static const unsigned char " .. name .. "[] = {"
    for i = 1, #bytes, 12 do
        local chunk = {}
        for j = i, math.min(i + 11, #bytes) do
            chunk[#chunk + 1] = bytes[j]
        end
        lines[#lines + 1] = "    " .. table.concat(chunk, ", ") .. ","
    end
    lines[#lines + 1] = "};"
    lines[#lines + 1] = "static const size_t " .. name .. "_size = sizeof(" .. name .. ");"
    return table.concat(lines, "\n")
end

function M.generateSource(opts)
    opts = opts or {}
    if not opts.entry then
        error({
            type = "InvalidOptionsError",
            message = "entry is required",
        })
    end

    local bootstrap = cgen.generateBootstrap(opts)
    local template = readFile(opts.template_path or DEFAULT_TEMPLATE_PATH)
    return table.concat({
        "/* Generated by luainstaller. */",
        "#include <stddef.h>",
        emitBytes("luai_bootstrap", bootstrap),
        template,
        "",
    }, "\n\n")
end

return M
